/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
Example:
Input:s = "abcd", t = "abcde"
Output:e
Explanation:'e' is the letter that was added.
*/
/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 * use an array to store the char and occurances in t first, then go through s, decrease occurances till we found one char has one occurance left
 */
var findTheDifference = function(s, t) {
    var map = {};
    var arrS = s.split('');
    var arrT = t.split('');
    for(var i=0; i<arrT.length; i++) {
        map[arrS[i]] = map[arrS[i]] ? map[arrS[i]]+1 : 1;
        map[arrT[i]] = map[arrT[i]] ? map[arrT[i]]-1 : -1;
    }
    
    for(var key in map) {
        if(map[key] === -1) {
            return key;
        }
    }
};
