/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
Example:
Input:s = "abcd", t = "abcde"
Output:e
Explanation:'e' is the letter that was added.
*/
/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 * use an array to store the char and occurances in t first, then go through s, decrease occurances till we found one char has one occurance left
 */
var findTheDifference = function(s, t) {
    let map = new Map(), res;
    t.split("").forEach((c) =>{
         if(!map.has(c)) {
            map.set(c, 1);
         }
         else {
            map.set(c, map.get(c)+1);
         }
    }); 

     s.split("").forEach((c) => {
        if(map.has(c)) {
            map.set(c, map.get(c)-1);
        }
     }); 
     
     map.forEach((value, key)=>{
         if(value >0) {
             res= key;
         }
     });
     return res;
    
};
